name: Clang Build (Arch Linux)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arch container
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: --privileged
          args: "-v ${{ github.workspace }}:/workspace"
        
      - run: |
          echo "Workspace is located at ${{ github.workspace }}"

          # 更新系统并安装 依赖工具
          pacman -Syu --noconfirm
          pacman -S --noconfirm gcc clang cmake make

          # 确认工具版本
          g++ --version
          clang++ --version

      - name: Configure
        run: |
          cmake -B ${{github.workspace}}/build -G Ninja
           
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -j 1 -V