name: Build Test (From Arch Linux)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    strategy:
      matrix:
        mode: [Release, Debug]
        c_compiler: [gcc, clang]
        cpp_compiler: [g++, clang++]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装环境
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm gcc clang cmake ninja pkgconf openssl

      - name: 确认工具版本
        run: |
          g++ --version
          clang++ --version
          openssl version

      - name: Configure
        run: |
          cmake -B $(pwd)/build -S $(pwd) -G Ninja \
            -DCMAKE_BUILD_TYPE=${{matrix.mode}}
            -CMAKE_C_COMPILER=${{ matrix.c_compiler }}
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}

      - name: Build
        run: |
          cmake --build $(pwd)/build

      - name: Test
        run: |
          cd ./build
          ctest -T test
