name: C++20 Build (Arch Linux)

on:
push:
    branches:
    - main
pull_request:

jobs:
build:
    runs-on: ubuntu-latest  # Actions 运行环境, 实际工作在容器中完成
    steps:
    - name: Checkout code
        uses: actions/checkout@v3

    - name: Set up Arch container
        uses: addnab/docker-run-action@v3
        with:
        image: archlinux:latest
        options: --privileged  # 如果需要安装复杂依赖, 可添加权限
        run: |
            pacman -Syu --noconfirm  # 更新系统
            pacman -S --noconfirm gcc clang cmake make  # 安装工具链
            g++ --version  # 验证 GCC
            clang++ --version  # 验证 Clang
            mkdir build && cd build
            cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_STANDARD=20
            make
