name: Build Test (From Arch Linux)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装环境
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm gcc clang cmake ninja pkgconf openssl

      - name: 确认工具版本
        run: |
          g++ --version
          clang++ --version
          openssl version

  gcc-test:
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure with GCC
        run: |
          cmake -B $(pwd)/build -S $(pwd) -G Ninja -DCMAKE_CXX_COMPILER=g++

      - name: Build with GCC
        run: |
          cmake --build $(pwd)/build

      - name: Test with GCC
        run: |
          cd ./build
          ctest -T test

  clang-test:
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure with Clang
        run: |
          cmake -B $(pwd)/build -S $(pwd) -G Ninja -DCMAKE_CXX_COMPILER=clang++

      - name: Build with Clang
        run: |
          cmake --build $(pwd)/build

      - name: Test with Clang
        run: |
          cd ./build
          ctest -T test
