name: Bazel-GCC Build (Arch Linux)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arch container
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: --privileged
          args: "-v ${{ github.workspace }}:/workspace"
      - run: |
          cd /workspace
          # 更新系统并安装 Bazel 和依赖工具
          pacman -Syu --noconfirm
          pacman -S --noconfirm gcc clang cmake make bazel

          # 确认工具版本
          g++ --version
          clang++ --version
          bazel --version

          # 构建目标
          bazel build --config=gcc-cl //...

      - name: Test
        run: |
          cd /workspace
          # 运行 Bazel 测试目标
          bazel test --config=gcc-cl --test_output=errors //... 

      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: /root/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('**/WORKSPACE', '**/BUILD') }}
          restore-keys: |
            ${{ runner.os }}-bazel-