name: Build Test (From Windows MSVC)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  MSVC:
    runs-on: windows-latest
    strategy:
      matrix:
        mode: [Release, Debug]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装工具链 (通过 vsdevcmd)
        uses: ilammy/msvc-dev-cmd@v1

      - name: 配置
        run: |
          cmake -B "${{github.workspace}}/build" -S "${{github.workspace}}" -G "Ninja" ^
            -DCMAKE_BUILD_TYPE=${{matrix.mode}} ^
            -DCMAKE_C_COMPILER=cl.exe ^
            -DCMAKE_CXX_COMPILER=cl.exe

      - name: 构建
        run: |
          cmake --build "${{github.workspace}}/build"

      - name: 测试
        run: |
          cd build
          ctest -T test --output-on-failure
